# Generated by Django 5.2.7 on 2025-10-22 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pqr', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.administrativo'),
        ),
        migrations.AddField(
            model_name='queja',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ciudadano'),
        ),
        migrations.AddField(
            model_name='queja',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqr.estadoqueja'),
        ),
        migrations.AddField(
            model_name='queja',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tecnico'),
        ),
        migrations.AddField(
            model_name='comentarioqueja',
            name='queja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='pqr.queja'),
        ),
        migrations.AddField(
            model_name='queja',
            name='tipo_falla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqr.tipofalla'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='usuarios.ciudadano'),
        ),
        migrations.AddField(
            model_name='queja',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='pqr.ubicacion'),
        ),
    ]
